refactor(jakarta): migrate from javax to jakarta packages for Spring Boot 3 compatibility
Addressed build failure in 'fiat-github:compileJava'. This issue arises as Spring Boot 3 now relies on Jakarta packages instead of javax.

* Error Details:
fiat/fiat-github/src/main/java/com/netflix/spinnaker/fiat/roles/github/GitHubProperties.java:3: error: package javax.validation.constraints does not exist
import javax.validation.constraints.Max;
                                   ^
fiat/fiat-github/src/main/java/com/netflix/spinnaker/fiat/roles/github/GitHubProperties.java:4: error: package javax.validation.constraints does not exist
import javax.validation.constraints.Min;
                                   ^
fiat/fiat-github/src/main/java/com/netflix/spinnaker/fiat/roles/github/GitHubProperties.java:5: error: package javax.validation.constraints does not exist
import javax.validation.constraints.NotEmpty;
                                   ^
fiat/fiat-github/src/main/java/com/netflix/spinnaker/fiat/roles/github/GitHubProperties.java:6: error: package javax.validation.constraints does not exist
import javax.validation.constraints.NotNull;

Reference Links:
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#jakarta-ee