refactor(jedis): Addressed compilation errors after upgrading to Spring Boot 3.0.13
After upgrading to Spring Boot 3.0.13, the project encountered compilation issues due to breaking changes in Jedis. Spring Boot 2 uses Jedis 3, while Spring Boot 3 uses Jedis 4, which introduced the following errors:

fiat/fiat-roles/src/main/java/com/netflix/spinnaker/fiat/permissions/RedisPermissionsRepository.java:46: error: cannot find symbol
import redis.clients.jedis.commands.BinaryJedisCommands;
                                   ^
  symbol:   class BinaryJedisCommands
  location: package redis.clients.jedis.commands

fiat/fiat-roles/src/main/java/com/netflix/spinnaker/fiat/permissions/RedisPermissionsRepository.java:580: error: cannot find symbol
  private <T> T redisRead(TimeoutContext timeoutContext, Function<BinaryJedisCommands, T> fn) {
                                                                  ^
  symbol:   class BinaryJedisCommands
  location: class RedisPermissionsRepository
In Jedis 4, BinaryJedisCommands was removed, and its functionality was merged into JedisBinaryCommands. Updated the codebase to replace references to BinaryJedisCommands with JedisBinaryCommands, resolving these errors and ensuring compatibility with the latest library version.