refactor(jakarta): Replaced the use of WebSecurityConfigurerAdapter with a configuration that defines SecurityFilterChain bean.
The error occurs because WebSecurityConfigurerAdapter has been deprecated and removed in Spring Security 6.x, which is used by Spring Boot 3.x.

Error details for reference:
````
> Task :fiat-api:compileJava
/home/rahul/Documents/codebase/spinnaker/fiat/fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatAuthenticationConfig.java:46: error: cannot find symbol
import org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter;
                                                                       ^
  symbol:   class WebSecurityConfigurerAdapter
  location: package org.springframework.security.config.annotation.web.configuration
/home/rahul/Documents/codebase/spinnaker/fiat/fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatAuthenticationConfig.java:128: error: cannot find symbol
  private static class FiatWebSecurityConfigurerAdapter extends WebSecurityConfigurerAdapter {
                                                                ^
  symbol:   class WebSecurityConfigurerAdapter
  location: class FiatAuthenticationConfig
````
Reference Links:
https://spring.io/blog/2022/02/21/spring-security-without-the-websecurityconfigureradapter