refactor(jakarta): migrate from javax to jakarta packages for Spring Boot 3 compatibility
Addressed build failure by replacing jakarta with javax. This issue arises as Spring Boot 3 now relies on Jakarta packages instead of javax.

Attached a portion of error logs for reference:
fiat/fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/AuthenticatedRequestAuthenticationConverter.java:21: error: package javax.servlet.http does not exist
import javax.servlet.http.HttpServletRequest;
                         ^
fiat/fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/AuthenticatedRequestAuthenticationConverter.java:36: error: cannot find symbol
  public Authentication convert(HttpServletRequest request) {
                                ^
  symbol:   class HttpServletRequest
  location: class AuthenticatedRequestAuthenticationConverter
fiat/fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatAuthenticationConverter.java:23: error: package javax.servlet.http does not exist
import javax.servlet.http.HttpServletRequest;
                         ^
fiat/fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatAuthenticationConverter.java:40: error: cannot find symbol
  public Authentication convert(HttpServletRequest request) {
                                ^
  symbol:   class HttpServletRequest
  location: class FiatAuthenticationConverter

Reference Links:
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#jakarta-ee